### ISSUE TITLE
ball = PVector(random(20,680),random(20,680))

### ISSUE THREAD

**Issue by Johnson321321** [Gallo-ICS2O1a/repel-assignment-johnson-tristan#2]
ballsize = 40
speed=PVector(2,2)
score=0
playersize=40

def setup():
    size(700,700)
def draw():
    global ball
    global ballsize
    global speed
    global score
    background(0)
    fill(255)
    ellipse(ball.x,ball.y,ballsize,ballsize)
    #Points
    playerball = PVector(mouseX,mouseY) 
    fill(255,0,0)
    ellipse(playerball.x,playerball.y,playersize,playersize)
    distance = PVector.sub(ball,playerball)
    if distance.mag() <= 80:
        ball+=speed
   
    fill(255)
    textSize(50)
    text('''Score''' + str(score),50,50)

**Comment by MrGallo** [comment]
...
